### ISSUE TITLE
Build fails on arm and ppc architectures

### ISSUE THREAD

**Issue by lgbaldoni** [Bollos00/LibreMines#10]
See [log snippet](https://github.com/Bollos00/LibreMines/files/5716016/libremines-ppc64.txt).
Using openSUSE Tumbleweed.

**Comment by Bollos00** [comment]
Changing the type `char` to `qint8` (also known as `signed char`) must solve this issue.

I have pushed a [new commit](https://github.com/Bollos00/LibreMines/commit/dc2cd59bd9453d9d667890567f03f58e64419cd0), could you check if it is solved now, please?

**Comment by lgbaldoni** [comment]
I confirm it does, TYVM.
