### ISSUE TITLE
The lack of sound effects...

### ISSUE THREAD

**Issue by SecularSteve** [Bollos00/LibreMines#39]
I mean, it would be nice to have an option for it.

I could volunteer on some aspects.
This isn't "Mime-sweeper" you know.

Here's my proposals:

Game start sounds:
https://freesound.org/people/andersmmg/sounds/511492/
https://freesound.org/people/aabbccddee123/sounds/469963/

The clock ticking sounds:
https://freesound.org/people/anthonychartier2020/sounds/341278/
https://freesound.org/people/ironcross32/sounds/582695/

The mine explosion sounds:
https://freesound.org/people/JohanDeecke/sounds/369529/
https://freesound.org/people/SamsterBirdies/sounds/580040/
https://freesound.org/people/Nbs%20Dark/sounds/94185/

The "winner sunglasses" sounds:
https://freesound.org/people/danlucaz/sounds/569894/
https://freesound.org/people/davidkyoku/sounds/133999/
https://freesound.org/people/EchoCinematics/sounds/392465/

**Comment by Bollos00** [comment]
> I could volunteer on some aspects.

On what aspects?

**Comment by SecularSteve** [comment]
> On what aspects?

A couple of my own themes.
Maybe designing the sounds myself if none of them are adequate, or licence compatible.
But that's just me...

**Comment by Bollos00** [comment]
Well, sure. I thing it would be great.

And about the license compatibility, all the tracks that you sent seen to be okay.

**Comment by Bollos00** [comment]
Hello @SecularSteve,

I worked on the implementation of the sound effects on the last few days. Here is the current behaviour of the game when the 'sound effects' option is enabled (I will still create that option).

https://user-images.githubusercontent.com/53309405/152611984-91c73469-985a-44bb-b37e-05c274ad70d4.mp4

The 'clock ticking' sound made the game too loud in my opinion, so I did not use that one and, instead, I used the sound effect of when the user clicks on the cell to release it, flag or unflag a cell and move with the controller towards the board.

Feel free to give me feedback of the sound effects, I like very much the sound of when the game ends, but I am still not so confident about the others. What do you think?

**Comment by SecularSteve** [comment]
Not bad... 👌

All that's left is to make the time counter the same layout as the "amount of flags left" counter, but with a clear "0:00:00" start point ("H:MM:SS")
