### ISSUE TITLE
A few bugs found and feature requests

### ISSUE THREAD

**Issue by Jon-guy30** [Bollos00/LibreMines#50]
In my quest finding a free software implementation of minesweeper I've come across this game, LibreMines. Since this project appears quite small I'll post my "problems" in a list format rather than have them one thread at a time.

1. There's a bug at least on Windows when clicking on a number it acts like I clicked at a mine if the number is adjacent to a mine leading to game loss.
2. The app window doesn't scale properly resizing the window leading to funny scrollbars in the board.
3. I'd also like a little bit of a smaller board while playing, currently it's a bit in-your-face. Goes hand in hand with the scaling issue, more customization of the size (I'd like to be able to "zoom out" in-game) of the board itself would be nice! Take inspiration from the Microsoft minesweeper, the classic one, well maybe not that one, that's a little bit TOO small. :P
4. There's a typo in the readme, in the "Playing with the keyboard" section where it says to restart the game with CTRL + R it should say to restart the game, instead it says to re**t**art the game, otherwise good grammar.
5. I noticed in the custom games, it's limited to 10x10? I'd like to be able to play 8x8 the standard easy board but with more mines, that would be cool.

That's all for now, time for screenshots!

When clicking a number close to a mine...
![Clicking a number](https://github.com/Bollos00/LibreMines/assets/10241225/03b45b41-5f4e-4eb0-83cc-b216f5cfcef4)

Boom!
![You lose!](https://github.com/Bollos00/LibreMines/assets/10241225/05d34aa3-9915-4f20-9388-068406ac95dc)

Scaling problem.
![Improper Scaling](https://github.com/Bollos00/LibreMines/assets/10241225/4da99349-97cd-40c9-a06f-a639c32c98ec)

**Comment by Bollos00** [comment]
Hello @Jon-guy30,

Thank you for bringing those items to my attention and sorry for my enormous delay in replying to you.

Regarding item 1, there is an option on settings (set to enabled by default) which enables this feature of clearing adjacent blank cells when clicking on a number cell. This usually helps on clearing the board faster, but can be unpleasant when undesired.

Regarding item 3, there is an option on settings which enable you to limit the board game to some specific size, this should be a workaround.

![Screenshot 2024-01-05 090416](https://github.com/Bollos00/LibreMines/assets/53309405/605c8ba8-e7d8-4170-b0b0-01f0a8acdf90)

Regarding the items 2, 4 and 5, I will start to work on those as soon as possible, thanks to bring them to my attention.
