### ISSUE TITLE
clicking on the number ends the game

### ISSUE THREAD

**Issue by viyyer** [Bollos00/LibreMines#60]
This is quite strange that the games ends every time I click any number twice. any bugfixes have been planned ?

**Comment by Bollos00** [comment]
Hello,

In the menu bar, under Options > Preferences... there is the option 'Clean neighbor cells when clicked on showed cell'
![image](https://github.com/user-attachments/assets/3277a6e1-4bad-4180-89e1-8afa3544c7dc)

This option clicks on all number cells that are not marked as a mine. I believe this option is enabled and causing this behavior.

**Comment by CarterSnich** [comment]
> Hello,
> 
> In the menu bar, under Options > Preferences... there is the option 'Clean neighbor cells when clicked on showed cell' ![image](https://github.com/user-attachments/assets/3277a6e1-4bad-4180-89e1-8afa3544c7dc)
> 
> This option clicks on all number cells that are not marked as a mine. I believe this option is enabled and causing this behavior.

But, double-clicking on a number that has number of flags the same with the number is not working. I remember spam clicking my mouse back when I'm playing on Vista.
